# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.grpbxInfuse1 = QtWidgets.QGroupBox(self.centralWidget)
        self.grpbxInfuse1.setGeometry(QtCore.QRect(10, 20, 241, 131))
        self.grpbxInfuse1.setObjectName("grpbxInfuse1")
        self.layoutWidget = QtWidgets.QWidget(self.grpbxInfuse1)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 197, 82))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnInfuseClose = QtWidgets.QPushButton(self.layoutWidget)
        self.btnInfuseClose.setObjectName("btnInfuseClose")
        self.horizontalLayout_2.addWidget(self.btnInfuseClose)
        self.btnInfuseOpen = QtWidgets.QPushButton(self.layoutWidget)
        self.btnInfuseOpen.setObjectName("btnInfuseOpen")
        self.horizontalLayout_2.addWidget(self.btnInfuseOpen)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblValveStateModifier = QtWidgets.QLabel(self.layoutWidget)
        self.lblValveStateModifier.setObjectName("lblValveStateModifier")
        self.horizontalLayout.addWidget(self.lblValveStateModifier)
        self.lblInfuseValveState = QtWidgets.QLabel(self.layoutWidget)
        self.lblInfuseValveState.setObjectName("lblInfuseValveState")
        self.horizontalLayout.addWidget(self.lblInfuseValveState)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblWeightDescriptor = QtWidgets.QLabel(self.layoutWidget)
        self.lblWeightDescriptor.setObjectName("lblWeightDescriptor")
        self.horizontalLayout_3.addWidget(self.lblWeightDescriptor)
        self.lblInfuseWeight = QtWidgets.QLabel(self.layoutWidget)
        self.lblInfuseWeight.setObjectName("lblInfuseWeight")
        self.horizontalLayout_3.addWidget(self.lblInfuseWeight)
        self.lblWeightUnits = QtWidgets.QLabel(self.layoutWidget)
        self.lblWeightUnits.setObjectName("lblWeightUnits")
        self.horizontalLayout_3.addWidget(self.lblWeightUnits)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.grpbxDrain = QtWidgets.QGroupBox(self.centralWidget)
        self.grpbxDrain.setGeometry(QtCore.QRect(10, 170, 241, 131))
        self.grpbxDrain.setObjectName("grpbxDrain")
        self.layoutWidget_2 = QtWidgets.QWidget(self.grpbxDrain)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 30, 197, 82))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnDrainClose = QtWidgets.QPushButton(self.layoutWidget_2)
        self.btnDrainClose.setObjectName("btnDrainClose")
        self.horizontalLayout_4.addWidget(self.btnDrainClose)
        self.btnDrainOpen = QtWidgets.QPushButton(self.layoutWidget_2)
        self.btnDrainOpen.setObjectName("btnDrainOpen")
        self.horizontalLayout_4.addWidget(self.btnDrainOpen)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lblValveStateModifier_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.lblValveStateModifier_2.setObjectName("lblValveStateModifier_2")
        self.horizontalLayout_5.addWidget(self.lblValveStateModifier_2)
        self.lblDrainValveState = QtWidgets.QLabel(self.layoutWidget_2)
        self.lblDrainValveState.setObjectName("lblDrainValveState")
        self.horizontalLayout_5.addWidget(self.lblDrainValveState)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lblWeightDescriptor_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.lblWeightDescriptor_2.setObjectName("lblWeightDescriptor_2")
        self.horizontalLayout_6.addWidget(self.lblWeightDescriptor_2)
        self.lblDrainWeight = QtWidgets.QLabel(self.layoutWidget_2)
        self.lblDrainWeight.setObjectName("lblDrainWeight")
        self.horizontalLayout_6.addWidget(self.lblDrainWeight)
        self.lblWeightUnits_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.lblWeightUnits_2.setObjectName("lblWeightUnits_2")
        self.horizontalLayout_6.addWidget(self.lblWeightUnits_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.grpbxInfuse1.setTitle(_translate("MainWindow", "Infuse Bag"))
        self.btnInfuseClose.setText(_translate("MainWindow", "Close"))
        self.btnInfuseOpen.setText(_translate("MainWindow", "Open"))
        self.lblValveStateModifier.setText(_translate("MainWindow", "Valve is: "))
        self.lblInfuseValveState.setText(_translate("MainWindow", "Closed"))
        self.lblWeightDescriptor.setText(_translate("MainWindow", "Current weight: "))
        self.lblInfuseWeight.setText(_translate("MainWindow", "100"))
        self.lblWeightUnits.setText(_translate("MainWindow", "g"))
        self.grpbxDrain.setTitle(_translate("MainWindow", "Drain Bag"))
        self.btnDrainClose.setText(_translate("MainWindow", "Close"))
        self.btnDrainOpen.setText(_translate("MainWindow", "Open"))
        self.lblValveStateModifier_2.setText(_translate("MainWindow", "Valve is: "))
        self.lblDrainValveState.setText(_translate("MainWindow", "Closed"))
        self.lblWeightDescriptor_2.setText(_translate("MainWindow", "Current weight: "))
        self.lblDrainWeight.setText(_translate("MainWindow", "100"))
        self.lblWeightUnits_2.setText(_translate("MainWindow", "g"))

